const DATA={
"fixed-prosthesis":{title:"Fixed Prosthesis",mark:"FP",intro:"Digitally engineered crowns, bridges and full-arch restorations designed for dependable fit, long-term performance and natural aesthetics.",overview:"Iconic Dental supports laboratories with a complete fixed-prosthesis design workflow. Every restoration is tailored to the clinical prescription and prepared for predictable production using advanced CAD tools.",products:[
["Crown & Bridge","Reliable crown and bridge designs created in Exocad and 3Shape with close attention to margins, contacts, occlusion and turnaround."],
["Screw-Retained","Stable, retrievable implant restorations customized around the implant position, access channel and clinical requirements."],
["Anatomical Coping","CAD/CAM copings shaped to follow natural tooth anatomy while supporting functional and aesthetic veneering."],
["Facial Cutback","Facial-only and mamelon cutbacks combining digital precision with room for controlled ceramic characterization."]]},
"digital-dentures":{title:"Digital Dentures",mark:"DD",intro:"Removable prosthodontic designs built for accurate fit, patient comfort, natural aesthetics and efficient digital fabrication.",overview:"From complete dentures to flexible and removable partials, Iconic Dental designs patient-specific removable solutions that replace missing teeth and soft tissue while integrating smoothly into the lab workflow.",products:[
["Digital Dentures","Fully customized digital denture designs developed for fit, comfort, balanced occlusion and natural appearance."],
["Flexible Partial Dentures","Flexible partial designs shaped to blend with natural dentition while supporting comfortable and secure daily wear."],
["Removable Partial Dentures","Digitally designed RPDs tailored for accurate support, retention, function and predictable manufacturing."]]},
"night-guards-and-splints":{title:"Night Guards & Splints",mark:"NG",intro:"Protective appliances digitally designed for precise fit, comfortable wear and reliable defense against grinding, impact and dental stress.",overview:"Iconic Dental creates custom night guards, bite splints and specialized removable appliances for a wide range of clinical requirements. Each design prioritizes comfort, durability and seamless laboratory production.",products:[
["Night Guards","Patient-specific guards designed to protect against grinding and clenching while maintaining comfortable wear."],
["Mouth Guards","Custom appliance designs supporting protection for bruxism, TMJ-related requirements and general dental stress."],
["Sport Guards","Protective sports guards tailored for retention, comfort and impact protection during physical activity."],
["Snap-On Smile","Removable cosmetic appliance designs created with CAD technology for accurate fit and a natural appearance."]]},
"implants":{title:"Implants",mark:"IM",intro:"Precision implant designs engineered for fit, function and aesthetics across custom abutments, full-arch cases and implant-supported restorations.",overview:"Iconic Dental works with dental labs to create tailored implant solutions compatible with leading systems. Advanced digital workflows help deliver stable, maintainable and production-ready designs for each clinical situation.",products:[
["Custom Abutments","Patient-specific abutments designed around anatomy, tissue support, restorative space and long-term stability."],
["All-on-X","Full-arch implant designs customized for strength, comfort, hygiene access and natural-looking restorative outcomes."],
["Implant Bars","Accurate bar designs providing a stable foundation for implant-supported removable and fixed solutions."]]},
"cosmetic-dentistry":{title:"Cosmetic Dentistry",mark:"CD",intro:"Aesthetic dental designs balancing proportion, symmetry, translucency and anatomy for confident, natural-looking smile transformations.",overview:"Iconic Dental helps laboratories visualize and produce aesthetic cases with digitally planned wax-ups and veneers. Every design is tailored to surrounding dentition and the intended restorative result.",products:[
["Digital Wax-Up","Highly accurate diagnostic wax-ups that support visualization, treatment planning and controlled adjustment before production."],
["Veneers","Custom veneer designs developed for fit, natural translucency, harmonious proportions and durable aesthetics."]]},
"models":{title:"Models",mark:"MO",intro:"Accurate, reproducible digital dental models prepared for diagnostics, treatment planning, communication and dependable lab production.",overview:"Iconic Dental creates detailed digital models that capture the patient’s dentition for reliable printing and clinical-laboratory workflows. Each model is optimized for its intended diagnostic or production purpose.",products:[
["Full Arch Models","Complete-arch models accurately representing dentition for comprehensive planning and laboratory use."],
["Quadrant Models","Focused models of a specific quadrant for targeted diagnostics, restorative planning and communication."],
["Contact Models","Durable digital models engineered to present interproximal contact relationships with clarity and precision."]]}
};
const key=document.body.dataset.service,d=DATA[key];
const servicesLink=[...document.querySelectorAll(".links>a")].find(a=>a.textContent.trim()==="Services");
if(servicesLink){const drop=document.createElement("div");drop.className="detail-drop";drop.innerHTML=`<a href="design-services.html">Services</a><div class="detail-menu"><div class="detail-group"><a href="design-services.html">Design Services</a><div class="detail-submenu"><a href="fixed-prosthesis.html">Fixed Prosthesis</a><a href="digital-dentures.html">Digital Dentures</a><a href="night-guards-and-splints.html">Night Guards &amp; Splints</a><a href="implants.html">Implants</a><a href="cosmetic-dentistry.html">Cosmetic Dentistry</a><a href="models.html">Models</a></div></div><div class="detail-group"><a href="iconic-dental_5.html#services">Dental Lab</a><div class="detail-submenu"><a href="iconic-dental_5.html#services">Explore all products</a><a href="#">Zirconia Crowns</a><a href="#">All-on-X Hybrids</a><a href="#">e.max Restorations</a><a href="#">PFM Crowns</a><a href="#">Surgical Guides</a><a href="#">Night Guards</a><a href="#">Printed Models &amp; Dies</a></div></div></div>`;servicesLink.replaceWith(drop);}
const IMAGES={
"fixed-prosthesis":["FIXED_PROSTHESIS_x2akap.png","FIXED_PROSTHESIS-1_fid575.png","Screw-Retained_rjmikx.png","Anatomical_Coping_guichx.png","Facial_Cutback__vycitp.png"],
"digital-dentures":["Removable_Partial_Dentures_y3ygvi.png","Digital_Dentures_tpwral.png","Flexible_Partial_Dentures_FPD_jzyuzh.png","Removable_Partial_Dentures_y3ygvi.png"],
"night-guards-and-splints":["Appliances_Splints_page_banner_kdotjy.png","Appliances_Splints_page_banner_kdotjy.png","Mouth_Guards_f5otjy.png","Sports_Guard_vj8bp4.png","Snap_on_Smile_fdgeuf.png"],
"implants":["IMPLANT_BARS_hmv1lk.png","Custom_Abutments_fsperx.png","ALL_ON_X_ypbmev.png","IMPLANT_BARS_hmv1lk.png"],
"cosmetic-dentistry":["Cosmetic_Dentistry_qpitob.png","Digital_Wax-Up_yailto.png","Veneers_l22fpy.png"],
"models":["Quadrant_Models_qpiazq.png","Full_Arch_with_articulatorV_qrlonc.png","Quadrant_Models_qpiazq.png","Contact_Models_i7ppr4.png"]};
const cloud=name=>`https://res.cloudinary.com/dbwuxxypx/image/upload/${name}`;
const FEATURES={"fixed-prosthesis":["Case-specific margins and contacts","Occlusion and anatomy reviewed","Production-ready CAD output"],"digital-dentures":["Patient-specific base and tooth setup","Fit, comfort and function considered","Optimized for digital fabrication"],"night-guards-and-splints":["Accurate appliance fit","Balanced contacts and guidance","Print-ready digital workflow"],"implants":["Implant position and access considered","Restorative space carefully managed","Compatible with leading workflows"],"cosmetic-dentistry":["Proportion and symmetry refined","Natural anatomy and aesthetics","Designed around the clinical plan"],"models":["Detailed anatomical reproduction","Printability and accuracy reviewed","Reliable diagnostic foundation"]};
document.title=`${d.title} Design | Iconic Dental`;
document.querySelectorAll("#title").forEach(el=>el.textContent=d.title);document.querySelector("#mark").innerHTML=`<img src="${cloud(IMAGES[key][0])}" alt="${d.title}">`;document.querySelector("#intro").textContent=d.intro;document.querySelector("#overview").textContent=d.overview;
document.querySelector("#products").innerHTML=d.products.map((p,i)=>`<article class="product"><div class="product-img"><img src="${cloud(IMAGES[key][i+1])}" alt="${p[0]}" loading="lazy"></div><div class="product-body"><span class="num">/ ${String(i+1).padStart(2,"0")}</span><h3>${p[0]}</h3><p>${p[1]} Each case is interpreted around the prescription, available restorative space and your laboratory preferences, creating a consistent path from digital approval to final production.</p><ul class="product-features">${FEATURES[key].map(x=>`<li>${x}</li>`).join("")}</ul><a href="#contact">Enquire now <span>→</span></a></div></article>`).join("");
const faqs=[`What ${d.title.toLowerCase()} design services does Iconic Dental provide?`,`What is the design process for ${d.title.toLowerCase()} cases?`,`What turnaround options are available?`,`How does Iconic Dental check design quality and accuracy?`,`Are the files compatible with leading CAD/CAM workflows?`];
document.querySelector("#faqs").innerHTML=faqs.map((q,i)=>`<details${i===0?" open":""}><summary>${q}</summary><p>Our team reviews the prescription and scan data, designs the case in leading dental CAD software, applies quality control and returns production-ready files through your agreed workflow.</p></details>`).join("");
const sharedNavStyle=document.createElement("link");sharedNavStyle.rel="stylesheet";sharedNavStyle.href="shared-navbar.css";document.head.appendChild(sharedNavStyle);const sharedNavScript=document.createElement("script");sharedNavScript.src="shared-navbar.js";document.body.appendChild(sharedNavScript);const sharedFooterScript=document.createElement("script");sharedFooterScript.src="shared-footer.js";document.body.appendChild(sharedFooterScript);
