(()=>{
  const old=document.querySelector("header.nav");if(!old)return;
  const labLinks=`<a href="dental-lab-services.html">Explore all products</a><a href="zirconia-crowns.html">Zirconia Crowns</a><a href="all-on-x-hybrids.html">All-on-X Hybrids</a><a href="e-max-restorations.html">e.max Restorations</a><a href="pfm-crowns.html">PFM Crowns</a><a href="surgical-guides.html">Surgical Guides</a><a href="night-guards.html">Night Guards</a><a href="printed-models-dies.html">Printed Models &amp; Dies</a>`;
  old.outerHTML=`<header class="site-nav"><div class="site-nav-wrap"><a class="site-logo" href="iconic-dental_5.html"><img src="Asset%203@3x.png" alt="Iconic Dental"></a><nav class="site-links"><div class="site-drop"><a class="site-trigger" href="design-services.html">Services</a><div class="site-menu"><div class="site-sub"><a href="design-services.html">Design Services</a><div class="site-submenu"><a href="fixed-prosthesis.html">Fixed Prosthesis</a><a href="digital-dentures.html">Digital Dentures</a><a href="night-guards-and-splints.html">Night Guards &amp; Splints</a><a href="implants.html">Implants</a><a href="cosmetic-dentistry.html">Cosmetic Dentistry</a><a href="models.html">Models</a></div></div><div class="site-sub"><a href="dental-lab-services.html">Dental Lab</a><div class="site-submenu">${labLinks}</div></div></div></div><div class="site-drop"><a class="site-trigger" href="iconic-dental_5.html#process">Learnings</a><div class="site-menu"><a href="#">Articles</a><a href="iconic-dental_5.html#testimonials">Customer Reviews</a></div></div><a href="iconic-dental_5.html#about">About Us</a><a href="#">Iconic Connect</a><div class="site-drop"><a class="site-trigger" href="iconic-dental_5.html#faq">Quick Links</a></div></nav><a class="site-cta" href="iconic-dental_5.html#contact">Start a case →</a><button class="site-burger" aria-label="Open menu"><span></span><span></span><span></span></button></div></header><div class="site-mobile"><div class="site-mobile-top"><a class="site-logo" href="iconic-dental_5.html"><img src="Asset%203@3x.png" alt="Iconic Dental"></a><button class="site-mobile-close">×</button></div><a href="design-services.html">Services</a><a class="sub-link" href="design-services.html">Design Services</a><a class="deep-link" href="fixed-prosthesis.html">Fixed Prosthesis</a><a class="deep-link" href="digital-dentures.html">Digital Dentures</a><a class="deep-link" href="night-guards-and-splints.html">Night Guards &amp; Splints</a><a class="deep-link" href="implants.html">Implants</a><a class="deep-link" href="cosmetic-dentistry.html">Cosmetic Dentistry</a><a class="deep-link" href="models.html">Models</a><a class="sub-link" href="dental-lab-services.html">Dental Lab — Explore all products</a><a class="deep-link" href="zirconia-crowns.html">Zirconia Crowns</a><a class="deep-link" href="all-on-x-hybrids.html">All-on-X Hybrids</a><a class="deep-link" href="e-max-restorations.html">e.max Restorations</a><a class="deep-link" href="pfm-crowns.html">PFM Crowns</a><a class="deep-link" href="surgical-guides.html">Surgical Guides</a><a class="deep-link" href="night-guards.html">Night Guards</a><a class="deep-link" href="printed-models-dies.html">Printed Models &amp; Dies</a><a href="iconic-dental_5.html#process">Learnings</a><a href="iconic-dental_5.html#about">About Us</a><a href="#">Iconic Connect</a><a href="iconic-dental_5.html#faq">Quick Links</a><a class="site-cta" href="iconic-dental_5.html#contact">Start a case →</a></div>`;
  const quickTrigger=[...document.querySelectorAll('.site-nav .site-trigger')].find(a=>a.textContent.trim()==='Quick Links');
  if(quickTrigger){
    quickTrigger.parentElement.insertAdjacentHTML('beforeend','<div class="site-menu"><a href="download-rx-form.html">Download Rx Form</a><a href="shipping-label.html">Shipping Label</a><a href="track-case.html">Track Case</a></div>');
  }
  const mobileQuick=[...document.querySelectorAll('.site-mobile>a')].find(a=>a.textContent.trim()==='Quick Links');
  if(mobileQuick){
    mobileQuick.insertAdjacentHTML('afterend','<a class="deep-link" href="download-rx-form.html">Download Rx Form</a><a class="deep-link" href="shipping-label.html">Shipping Label</a><a class="deep-link" href="track-case.html">Track Case</a>');
  }
  [...document.querySelectorAll('.site-nav a,.site-mobile a')].filter(a=>a.textContent.trim()==='Articles').forEach(a=>a.href='articles.html');
  const m=document.querySelector('.site-mobile');document.querySelector('.site-burger').onclick=()=>{m.classList.add('open');document.body.style.overflow='hidden'};document.querySelector('.site-mobile-close').onclick=()=>{m.classList.remove('open');document.body.style.overflow=''};
  document.querySelectorAll('.site-nav a, .site-mobile a').forEach(a=>{
    if(a.textContent.trim()==='Customer Reviews') a.href='customer-reviews.html';
  });
})();
